language: haskell

sudo: false

git:
  depth: 5

cache:
  directories:
    - "$HOME/.cabal/store"

matrix:
  include:
    - ghc: 8.0.1
    - ghc: 8.2.2
    - ghc: 8.4.4
    - ghc: 8.6.5
    - ghc: 8.8.2

install:
  - cabal update
  - cabal install --only-dependencies --enable-tests ldap-client.cabal
  - npm install ldapjs

script:
  - cabal install --enable-tests $RUN_TESTS ldap-client.cabal
  - cabal sdist && cabal install --enable-tests dist/ldap-client-*.tar.gz
